### ISSUE TITLE
meta helper doesn't work

### ISSUE THREAD

**Issue by hendrasan** [edmundask/codeigniter-twiggy#11]
```
// controller
$this->twiggy->meta('description', 'description');

// twig
{{ meta }}
```

When I view the source, it generates blank row.

I debug it up to the point of this line

```
private function _load()
{
    $this->_globals['meta'] = $this->_compile_metadata();
    $this->_rendered = TRUE;

    return $this->_twig->loadTemplate($this->_template . $this->_config['template_file_ext']);
}
```

and when I `var_dump` the `$this->_globals['meta']`, the description meta is still there.

Any idea? Thanks

**Comment by edmundask** [comment]
Hi there,

sorry for not responding to this sooner, have been busy. :)

Yes, this seems to be a bug. At the moment I can't test it, but I'm pretty sure that instead of

```
$this->_globals['meta'] = $this->_compile_metadata();
```

there should be

```
$this->set('meta', $this->_compile_metadata(), true);
```

See if this works.

**Comment by hendrasan** [comment]
thanks!
