### ISSUE TITLE
Where I should place CSS, images and Scripts in order to access from layouts?

### ISSUE THREAD

**Issue by reypm** [edmundask/codeigniter-twiggy#17]
Can you give me a point about where I should place css, images and scripts in order to access from layouts? Also any code sample?

**Comment by lewispb** [comment]
You should create a 'themes' directory in the base directory of your Codeigniter project and within that your themename director, within that an assets folder and within that, css, img and js directories.
You can then store theme specific assets in the theme folder and shared assets in the root assets folder.

```
-- project
|    |-- application 
|    +--assets
|    |    |--css
|    |    |--img
|    |    |--js
|    |-- system
|    +-- themes
|    |    |--themename
|    |    |    |--assets
|    |    |    |    |--css
|    |    |    |    |--img
|    |    |    |    |--js
|    |-- index.php
```

Make sure you change line 151 in application/config/twiggy.php to:

``` php
151: $config['twiggy']['include_apppath'] = FALSE;
```
