### ISSUE TITLE
Sub Directories for Views/Templates

### ISSUE THREAD

**Issue by ghost** [edmundask/codeigniter-twiggy#4]
I would like to have the following directory structure to organize my app & views a bit better.. the following example is how i would like the layouts/templates to be organized. This is how i do it with my controllers.

``` text
- application
  - themes
    - default
      - _layouts
        - backend.html.twig //backend layout differs from the auth layout
        - auth.html.twig //auth layout has slightly different header and requires different js/css
      - auth //this is a sub folder, to house all teh template/views related to authentication
        - login.html.twig
        - change_password.html.twig
      - backend //this is a sub folder, to house all template/views related to the backend
        - index.html.twig
        - user //this is a sub folder, to house all template/views related to the user class
          - add.html.twig
          - edit.html.twig
          - index.html.twig
```

Is this possible? If not where can i get started so i can fork the repo and make the changes.

**Comment by RelativeMedia** [comment]
answered my own question, according to the code.. i can run:

``` php
$this->twiggy->layout('auth')->display('auth/login');
```

and that will load the `auth.html.twig` layout file, and then traverse through to the `auth/login.html.twig` template file.

this lib doesn't seem to care how deep you go either...

``` php
$this->twiggy->layout('backend')->display('backend/user/index');

```

Works as well
